FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
COPY .env .
COPY PDIKSListener/ PDIKSListener/

ENV PYTHONPATH=/app

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

ENV LOG_LEVEL=DEBUG

CMD ["python", "-u", "PDIKSListener/run_all.py"]
